### PR TITLE
fix(autotls): integration test nil pointer dereference

### LINKED ISSUE #1830: flaky test(autotls): nill pointer exception
https://github.com/vacp2p/nim-libp2p/actions/runs/18899437750/job/53943425481
```
[NimScript] exec: ./tests/testintegration --output-level=VERBOSE
[Suite  ] PeerID Auth
  [Test   ]           test peerID send
  [OK     ] (  2.52s) test peerID send
(2.52s)   PeerID Auth

[Suite  ] AutoTLS Integration
  [Test   ]           request challenge without ACMEClient (ACMEApi only)
  [OK     ] (  2.32s) request challenge without ACMEClient (ACMEApi only)
  [Test   ]           request challenge with ACMEClient
  [OK     ] (  1.82s) request challenge with ACMEClient
Traceback (most recent call last)
/home/runner/.nimble/pkgs2/unittest2-0.2.4-746106a4dfefffce497f1693733f1c1513b5c62c/unittest2.nim(1170) testautotls_integration
/home/runner/.nimble/pkgs2/unittest2-0.2.4-746106a4dfefffce497f1693733f1c1513b5c62c/unittest2.nim(1097) runDirect
/home/runner/work/nim-libp2p/nim-libp2p/tests/utils/async_tests.nim(29) runTest`gensym227
/home/runner/work/nim-libp2p/nim-libp2p/tests/testautotls_integration.nim(81) :anonymous
/home/runner/.nimble/pkgs2/chronos-4.0.4-455802a90204d8ad6b31d53f2efff8ebfe4c834a/chronos/internal/asyncmacro.nim(445) anonymous
SIGSEGV: Illegal storage access. (Attempt to read from nil?)
  [Test   ]           AutotlsService correctly downloads challenges
Segmentation fault (core dumped)
stack trace: (most recent call last)
/tmp/nimblecache-1194919871666104896/nimscriptapi_1807076757446332794.nim(219, 16)
/home/runner/work/nim-libp2p/nim-libp2p/libp2p.nimble(83, 10) testintegrationTask
/home/runner/work/nim-libp2p/nim-libp2p/libp2p.nimble(46, 3) runTest
/home/runner/work/nim-libp2p/nim-libp2p/nim/lib/system/nimscript.nim(264, 7) exec
/home/runner/work/nim-libp2p/nim-libp2p/nim/lib/system/nimscript.nim(264, 7) Error: unhandled exception: FAILED: ./tests/testintegration --output-level=VERBOSE [OSError]
       Tip: 282 messages have been suppressed, use --verbose to show them.
nimscriptwrapper.nim(166) execScript
```

### PR DESCRIPTION
**Pull request by gmelodie**
Successful CI run: https://github.com/vacp2p/nim-libp2p/actions/runs/19139306367
Fix #1830

### CODE REVIEW

File: tests/testautotls_integration.nim [hunk 1]
```diff
@@ -74,14 +74,15 @@ when defined(linux) and defined(amd64):
...
         challenge.dns01.token.len > 0
 
-    asyncTest "AutotlsService correctly downloads challenges":
-      let ip =
-        try:
-          getPublicIPAddress()
-        except:
-          skip() # host doesn't have public IPv4 address
-          return
+    # this needs to be outside of the test due to nim shenanigans
```
Comment (vladopajic) [inline tests/testautotls_integration.nim]: hmm i am not convinced by this, please explain

File: tests/testautotls_integration.nim [hunk 2]
```diff
@@ -106,14 +107,14 @@ when defined(linux) and defined(amd64):
         try:
           autotls = AutotlsService(service)
           break
-        except:
+        except ObjectConversionDefect:
```
Comment (vladopajic) [inline tests/testautotls_integration.nim]: catching a defect? as far as i can understand defect should to be caught

Comment (gmelodie) [reply tests/testautotls_integration.nim]: Any suggestions on how else to do this?

File: tests/testautotls_integration.nim [hunk 3]
```diff
@@ -106,14 +105,14 @@ when defined(linux) and defined(amd64):
...
           continue
```
Comment (vladopajic) [inline tests/testautotls_integration.nim]:
```suggestion
       if service is AutotlsService:
         autotls = AutotlsService(service)
         break
```

**Review by vladopajic — APPROVED** [review]
